name: Build EXE with PyInstaller

on:
  push:
    branches: [ main ]
  workflow_dispatch: # erlaubt manuelles Auslösen

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed gui.py

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: PapyrusPM-Windows
        path: dist/gui.exe
